from django.urls import path
from . import views
from . import billing
from . import email_tracking
from . import organization_views

urlpatterns = [
    path("", views.home, name="home"),
    path("signup/", views.signup, name="signup"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("settings/", views.settings_view, name="settings"),
    path("radars/", views.radar_list, name="radar_list"),
    path("radars/new/", views.radar_create, name="radar_create"),
    path("radars/preview/", views.radar_preview, name="radar_preview"),
    path("radars/<int:pk>/", views.radar_detail, name="radar_detail"),
    path("radars/<int:pk>/edit/", views.radar_edit, name="radar_edit"),
    path("radars/<int:pk>/toggle/", views.radar_toggle, name="radar_toggle"),
    path("radars/<int:pk>/delete/", views.radar_delete, name="radar_delete"),
    path("radars/<int:pk>/export/", views.radar_export_csv, name="radar_export_csv"),
    path("leads/", views.lead_list, name="lead_list"),
    path("leads/export/", views.lead_export_csv, name="lead_export_csv"),
    path("leads/<int:pk>/status/", views.lead_status, name="lead_status"),
    path("leads/<int:pk>/favorite/", views.lead_favorite, name="lead_favorite"),
    path("leads/<int:pk>/notes/", views.lead_notes, name="lead_notes"),
    path("companies/<str:gemi_number>/", views.company_detail, name="company_detail"),
    # Gemi Leads 2.0: organization-scoped, authorized only through gemiapp.organization_access.
    path("organizations/<int:organization_id>/opportunities/company/<int:company_id>/",
         organization_views.company_opportunity_page, name="organization_company_opportunity"),
    path("organizations/<int:organization_id>/opportunities/company/<int:company_id>/do-not-contact/",
         organization_views.company_do_not_contact, name="organization_company_do_not_contact"),
    path("organizations/<int:organization_id>/opportunities/<int:opportunity_id>/save/",
         organization_views.save_opportunity, name="organization_save_opportunity"),
    path("organizations/<int:organization_id>/opportunities/<int:opportunity_id>/assign/",
         organization_views.assign_opportunity, name="organization_assign_opportunity"),
    path("organizations/<int:organization_id>/opportunities/<int:opportunity_id>/status/",
         organization_views.change_opportunity_status, name="organization_opportunity_status"),
    path("organizations/<int:organization_id>/opportunities/<int:opportunity_id>/notes/",
         organization_views.add_opportunity_note, name="organization_add_opportunity_note"),
    path("organizations/<int:organization_id>/opportunities/<int:opportunity_id>/tasks/",
         organization_views.create_opportunity_task, name="organization_create_opportunity_task"),
    path("organizations/<int:organization_id>/opportunities/<int:opportunity_id>/tasks/<int:task_id>/complete/",
         organization_views.complete_opportunity_task, name="organization_complete_opportunity_task"),
    path("organizations/<int:organization_id>/notifications/", organization_views.notifications_page,
         name="organization_notifications"),
    path("organizations/<int:organization_id>/notifications/read-all/", organization_views.mark_all_notifications_read,
         name="organization_notifications_read_all"),
    path("organizations/<int:organization_id>/notifications/<int:notification_id>/read/",
         organization_views.mark_notification_read, name="organization_notification_read"),
    path("api/kads/", views.kad_search, name="kad_search"),
    path("export/", views.export_csv, name="export_csv"),
    path("verify/<uidb64>/<token>/", views.verify_email, name="verify_email"),
    path("resend-verification/", views.resend_verification, name="resend_verification"),
    path("unsubscribe/<token>/", views.unsubscribe, name="unsubscribe"),
    path("digest/<token>/export/", views.digest_export_csv, name="digest_export_csv"),
    path("outreach/unsubscribe/<token>/", views.outreach_unsubscribe, name="outreach_unsubscribe"),
    # Billing / Stripe
    path("pricing/", billing.pricing, name="pricing"),
    path("privacy/", views.privacy, name="privacy"),
    path("terms/", views.terms, name="terms"),
    path("api/stripe/create-checkout-session/", billing.create_checkout_session, name="create_checkout_session"),
    # GET-safe landing point after login when a plan was chosen while logged out.
    path("checkout/resume/", billing.resume_checkout, name="resume_checkout"),
    path("api/stripe/customer-portal/", billing.customer_portal, name="customer_portal"),
    path("api/stripe/cancel-subscription/", billing.cancel_subscription, name="cancel_subscription"),
    path("api/stripe/resume-subscription/", billing.resume_subscription, name="resume_subscription"),
    path("api/stripe/change-plan/", billing.change_plan, name="change_plan"),
    path("api/stripe/cancel-scheduled-downgrade/", billing.cancel_scheduled_downgrade, name="cancel_scheduled_downgrade"),
    path("api/stripe/webhook/", billing.stripe_webhook, name="stripe_webhook"),
    path("api/brevo/webhook/<str:token>/", email_tracking.brevo_webhook, name="brevo_webhook"),
]
