# Generated by Django 5.2.16 on 2026-08-02 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemi_number', models.CharField(db_index=True, max_length=24, unique=True, verbose_name='Αριθμός ΓΕΜΗ')),
                ('vat_number', models.CharField(blank=True, db_index=True, max_length=12, verbose_name='ΑΦΜ')),
                ('name', models.CharField(db_index=True, max_length=500, verbose_name='Επωνυμία')),
                ('trade_names', models.TextField(blank=True, verbose_name='Διακριτικοί τίτλοι')),
                ('legal_type', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Νομική μορφή')),
                ('status', models.CharField(blank=True, max_length=120, verbose_name='Κατάσταση')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ενεργή')),
                ('incorporation_date', models.DateField(db_index=True, verbose_name='Ημερομηνία σύστασης')),
                ('gemi_office', models.CharField(blank=True, max_length=300, verbose_name='Υπηρεσία ΓΕΜΗ')),
                ('prefecture', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='Περιφερειακή ενότητα')),
                ('municipality', models.CharField(blank=True, db_index=True, max_length=160, verbose_name='Δήμος')),
                ('city', models.CharField(blank=True, max_length=160, verbose_name='Πόλη')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Διεύθυνση')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='ΤΚ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Ιστοσελίδα')),
                ('activities', models.JSONField(blank=True, default=list, verbose_name='Δραστηριότητες')),
                ('raw_data', models.JSONField(blank=True, default=dict, editable=False)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Επιχειρήσεις',
                'ordering': ['-incorporation_date', '-gemi_number'],
            },
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('running', 'Σε εξέλιξη'), ('success', 'Επιτυχία'), ('failed', 'Αποτυχία')], default='running', max_length=12)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DigestPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Καθημερινά'), ('weekly', 'Εβδομαδιαία'), ('off', 'Ανενεργό')], default='daily', max_length=10)),
                ('legal_types', models.JSONField(blank=True, default=list)),
                ('prefectures', models.JSONField(blank=True, default=list)),
                ('only_active', models.BooleanField(default=True)),
                ('include_empty_digest', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digest_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DigestDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest_date', models.DateField(db_index=True)),
                ('company_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('sent', 'Εστάλη'), ('skipped', 'Παραλείφθηκε'), ('failed', 'Απέτυχε')], max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digest_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'digest_date'), name='unique_user_daily_digest')],
            },
        ),
    ]
