# Generated by Django 5.2.16 on 2026-08-15 08:30

import django.db.models.deletion
import json
import re
import unicodedata
from pathlib import Path
from django.db import migrations, models


def normalize_text(value):
    decomposed = unicodedata.normalize('NFD', value or '')
    return ' '.join(''.join(ch for ch in decomposed if unicodedata.category(ch) != 'Mn').upper().split())


def load_kad_catalog_and_company_activities(apps, schema_editor):
    ActivityCode = apps.get_model('gemiapp', 'ActivityCode')
    Company = apps.get_model('gemiapp', 'Company')
    CompanyActivity = apps.get_model('gemiapp', 'CompanyActivity')
    catalog_path = Path(__file__).resolve().parent.parent / 'data' / 'kad_2025.json'
    catalog = json.loads(catalog_path.read_text(encoding='utf-8'))
    ActivityCode.objects.bulk_create([
        ActivityCode(
            code=item['code'],
            normalized_code=item['normalized_code'],
            description=item['description'],
            source=item['source'],
            search_text=normalize_text(f"{item['code']} {item['normalized_code']} {item['description']}"),
        )
        for item in catalog
    ], batch_size=1000)

    records = []
    for company in Company.objects.iterator(chunk_size=500):
        seen = set()
        for activity in company.activities or []:
            code = re.sub(r'\D', '', str(activity.get('code') or ''))
            activity_type = str(activity.get('type') or '')
            identity = (code, activity_type)
            if not code or identity in seen:
                continue
            seen.add(identity)
            records.append(CompanyActivity(
                company_id=company.id,
                code=code,
                description=str(activity.get('description') or ''),
                activity_type=activity_type,
            ))
    CompanyActivity.objects.bulk_create(records, batch_size=1000)


def unload_kad_catalog_and_company_activities(apps, schema_editor):
    apps.get_model('gemiapp', 'CompanyActivity').objects.all().delete()
    apps.get_model('gemiapp', 'ActivityCode').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='ΚΑΔ')),
                ('normalized_code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('description', models.CharField(max_length=1000, verbose_name='Περιγραφή δραστηριότητας')),
                ('source', models.URLField(blank=True, max_length=500, verbose_name='Πηγή')),
                ('search_text', models.TextField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'ΚΑΔ',
                'verbose_name_plural': 'Κατάλογος ΚΑΔ',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='digestpreference',
            name='activity_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='CompanyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16, verbose_name='ΚΑΔ')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Περιγραφή')),
                ('activity_type', models.CharField(blank=True, max_length=80, verbose_name='Τύπος')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='gemiapp.company')),
            ],
            options={
                'ordering': ['company_id', 'code'],
                'constraints': [models.UniqueConstraint(fields=('company', 'code', 'activity_type'), name='unique_company_activity')],
            },
        ),
        migrations.RunPython(load_kad_catalog_and_company_activities, unload_kad_catalog_and_company_activities),
    ]
