# Generated by Django 5.2.16 on 2026-08-15 14:35

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0004_rename_demo_user_for_gemi_leads'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRadar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Όνομα Radar')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('name_query', models.CharField(blank=True, max_length=200, verbose_name='Λέξη στην επωνυμία')),
                ('prefectures', models.JSONField(blank=True, default=list, verbose_name='Περιφερειακές ενότητες')),
                ('legal_types', models.JSONField(blank=True, default=list, verbose_name='Νομικές μορφές')),
                ('only_active', models.BooleanField(default=True, verbose_name='Μόνο ενεργές επιχειρήσεις')),
                ('frequency', models.CharField(choices=[('daily', 'Καθημερινά'), ('weekly', 'Εβδομαδιαία'), ('off', 'Χωρίς email')], default='daily', max_length=10, verbose_name='Συχνότητα ενημέρωσης')),
                ('monitor_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Παρακολούθηση από')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_codes', models.ManyToManyField(blank=True, related_name='customer_radars', to='gemiapp.activitycode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_radars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserCompanyLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Νέο'), ('viewed', 'Προβλήθηκε'), ('contacted', 'Επικοινώνησα'), ('interested', 'Ενδιαφέρεται'), ('not_interested', 'Δεν ενδιαφέρεται'), ('archived', 'Αρχείο')], default='new', max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_leads', to='gemiapp.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-first_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='RadarMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_on', models.DateField(db_index=True)),
                ('matched_activity_codes', models.JSONField(blank=True, default=list)),
                ('match_reason', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radar_matches', to='gemiapp.company')),
                ('import_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radar_matches', to='gemiapp.importrun')),
                ('radar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='gemiapp.customerradar')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radar_matches', to='gemiapp.usercompanylead')),
            ],
            options={
                'ordering': ['-matched_on', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customerradar',
            index=models.Index(fields=['user', 'is_active'], name='radar_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='customerradar',
            index=models.Index(fields=['frequency', 'is_active'], name='radar_freq_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerradar',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), condition=models.Q(('deleted_at__isnull', True)), name='unique_active_user_radar_name_ci'),
        ),
        migrations.AddIndex(
            model_name='usercompanylead',
            index=models.Index(fields=['user', 'status', '-first_seen_at'], name='lead_user_status_seen_idx'),
        ),
        migrations.AddIndex(
            model_name='usercompanylead',
            index=models.Index(fields=['user', 'is_favorite'], name='lead_user_favorite_idx'),
        ),
        migrations.AddConstraint(
            model_name='usercompanylead',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='unique_user_company_lead'),
        ),
        migrations.AddIndex(
            model_name='radarmatch',
            index=models.Index(fields=['radar', '-matched_on'], name='match_radar_date_idx'),
        ),
        migrations.AddIndex(
            model_name='radarmatch',
            index=models.Index(fields=['lead', '-matched_on'], name='match_lead_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='radarmatch',
            constraint=models.UniqueConstraint(fields=('radar', 'company'), name='unique_radar_company_match'),
        ),
    ]
