# Generated by Django 5.2.16 on 2026-08-17 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0006_migrate_digest_preferences_to_radars'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='digestdelivery',
            name='unique_user_daily_digest',
        ),
        migrations.AddField(
            model_name='digestdelivery',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Καθημερινά'), ('weekly', 'Εβδομαδιαία')], default='daily', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='digestdelivery',
            constraint=models.UniqueConstraint(fields=('user', 'digest_date', 'frequency'), name='unique_user_digest_delivery'),
        ),
    ]
