# Generated by Django 5.2.16 on 2026-08-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0008_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(default='inactive', max_length=30),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='tier',
            field=models.CharField(choices=[('free', 'Free (Legacy)'), ('pro', 'Pro'), ('business', 'Business')], default='free', max_length=20),
        ),
    ]
