# Generated by Django 5.2.16 on 2026-08-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0010_usersubscription_complimentary_tier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='complimentary_tier',
            field=models.CharField(choices=[('none', 'None'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise / Real-Time')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='tier',
            field=models.CharField(choices=[('free', 'Free (Legacy)'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise / Real-Time')], default='free', max_length=20),
        ),
    ]
