# Generated by Django 5.2.16 on 2026-08-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0011_alter_usersubscription_complimentary_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='custom_radar_limit',
            field=models.IntegerField(blank=True, help_text='Custom radar limit set by Superadmin', null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='complimentary_tier',
            field=models.CharField(choices=[('none', 'None'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise / Real-Time'), ('custom', 'Custom / Enterprise')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='tier',
            field=models.CharField(choices=[('free', 'Free (Legacy)'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise / Real-Time'), ('custom', 'Custom / Enterprise')], default='free', max_length=20),
        ),
    ]
