# Generated by Django 5.2.16 on 2026-08-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0012_usersubscription_custom_radar_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='last_sent_company_id',
            field=models.IntegerField(default=0, help_text='ID of last sent intraday GEMI company'),
        ),
    ]
