# Generated by Django 5.2.16 on 2026-08-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0013_usersubscription_last_sent_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestdelivery',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Καθημερινά'), ('weekly', 'Εβδομαδιαία'), ('intraday', '3-ωρο / Real-Time'), ('manual_yesterday', 'Χειροκίνητο (Χθες)')], default='daily', max_length=30),
        ),
    ]
