# Generated by Django 5.2.16 on 2026-08-21 21:02

from django.db import migrations, models


def convert_weekly_to_daily(apps, schema_editor):
    """The weekly digest is gone. Anything still set to weekly falls back to daily rather than
    being left on a value the application no longer understands.

    DigestDelivery rows are deliberately untouched: that table is an audit log of what was actually
    sent, and rewriting it would both falsify history and collide with the
    (user, digest_date, frequency) unique constraint.
    """
    apps.get_model("gemiapp", "DigestPreference").objects.filter(frequency="weekly").update(frequency="daily")
    apps.get_model("gemiapp", "CustomerRadar").objects.filter(frequency="weekly").update(frequency="daily")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0016_backfill_digest_preferences'),
    ]

    operations = [
        migrations.RunPython(convert_weekly_to_daily, noop),
        migrations.AlterField(
            model_name='customerradar',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Καθημερινά'), ('off', 'Χωρίς email')], default='daily', max_length=10, verbose_name='Συχνότητα ενημέρωσης'),
        ),
        migrations.AlterField(
            model_name='digestdelivery',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Καθημερινά'), ('intraday', '3-ωρο / Real-Time'), ('manual_yesterday', 'Χειροκίνητο (Χθες)'), ('weekly', 'Εβδομαδιαία (καταργήθηκε)')], default='daily', max_length=30),
        ),
        migrations.AlterField(
            model_name='digestpreference',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Καθημερινά'), ('off', 'Ανενεργό')], default='daily', max_length=10),
        ),
    ]
