# Generated by Django 5.2.16 on 2026-08-23 14:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0017_remove_weekly_digest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300, verbose_name='Ονοματεπώνυμο')),
                ('normalized_name', models.CharField(db_index=True, editable=False, max_length=300)),
                ('reason', models.TextField(blank=True, help_text='Εσωτερική τεκμηρίωση του αιτήματος.', verbose_name='Σημείωση')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ημερομηνία αιτήματος')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, help_text='Κενό = απόκρυψη σε όλες τις επιχειρήσεις.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_suppressions', to='gemiapp.company', verbose_name='Μόνο για την επιχείρηση')),
            ],
            options={
                'verbose_name': 'Εναντίωση προσώπου',
                'verbose_name_plural': 'Εναντιώσεις προσώπων (άρθρο 21 ΓΚΠΔ)',
                'ordering': ['-requested_at'],
                'constraints': [models.UniqueConstraint(fields=('normalized_name', 'company'), name='unique_person_suppression'), models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('normalized_name',), name='unique_global_person_suppression')],
            },
        ),
    ]
