# Generated by Django 5.2.16 on 2026-08-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0019_create_cache_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digestdelivery',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Καθημερινά'), ('intraday', '3-ωρο / Priority Alerts'), ('manual_yesterday', 'Χειροκίνητο (Χθες)'), ('weekly', 'Εβδομαδιαία (καταργήθηκε)')], default='daily', max_length=30),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='complimentary_tier',
            field=models.CharField(choices=[('none', 'None'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise / Priority Alerts'), ('custom', 'Custom / Enterprise')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='tier',
            field=models.CharField(choices=[('free', 'Free (Legacy)'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise / Priority Alerts'), ('custom', 'Custom / Enterprise')], default='free', max_length=20),
        ),
    ]
