# Generated by Django 5.2.16 on 2026-08-27 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0020_alter_digestdelivery_frequency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOutreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Εστάλη'), ('failed', 'Απέτυχε')], default='sent', max_length=10)),
                ('sent_to', models.EmailField(blank=True, max_length=254)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outreach', to='gemiapp.company')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_outreach', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Επικοινωνία με επιχείρηση',
                'verbose_name_plural': 'Επικοινωνίες με επιχειρήσεις',
                'ordering': ['-created_at'],
            },
        ),
    ]
