# Generated by Django 5.2.16 on 2026-08-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0020_add_stripe_webhook_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='scheduled_change_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='scheduled_tier',
            field=models.CharField(blank=True, choices=[('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise / Real-Time')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_schedule_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
