# Generated by Django 5.2.16 on 2026-08-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0021_companyoutreach'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Απεγγραφή outreach',
                'verbose_name_plural': 'Απεγγραφές outreach',
                'ordering': ['-created_at'],
            },
        ),
    ]
