# Generated by Django 5.2.16 on 2026-08-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0021_subscription_schedule_fields'),
        ('gemiapp', '0022_outreachsuppression'),
    ]

    operations = [
    ]
