# Generated by Django 5.2.16 on 2026-08-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0023_merge_20260827_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='scheduled_tier',
            field=models.CharField(blank=True, choices=[('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise / Priority Alerts')], default=None, max_length=20, null=True),
        ),
    ]
