# Generated by Django 5.2.16 on 2026-08-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0024_alter_usersubscription_scheduled_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyoutreach',
            name='status',
            field=models.CharField(choices=[('pending', 'Σε ουρά'), ('sent', 'Εστάλη'), ('failed', 'Απέτυχε')], default='sent', max_length=10),
        ),
    ]
