# Generated by Django 5.2.16 on 2026-08-28 04:31
# Renumbered from 0022 -> 0026 and rebased onto 0025 after merging in the parallel
# CompanyOutreach/OutreachSuppression work (0021-0025) done on another machine.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0025_alter_companyoutreach_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEngagementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tag', models.CharField(blank=True, db_index=True, max_length=255)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
