# Generated by Django 5.2.16 on 2026-08-30 12:24

from django.db import migrations, models


def backfill_sent_at(apps, schema_editor):
    """Existing "sent" rows predate the field. created_at is the best available proxy for
    when they went out (before requeue_dropped_outreach, the two were minutes apart). Rows
    that requeue_dropped_outreach has since flipped back to "pending" are correctly left
    with sent_at=NULL by the status filter.
    """
    CompanyOutreach = apps.get_model("gemiapp", "CompanyOutreach")
    CompanyOutreach.objects.filter(status="sent", sent_at__isnull=True).update(
        sent_at=models.F("created_at")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0027_normalize_engagement_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyoutreach',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_sent_at, migrations.RunPython.noop),
    ]
