# Generated by Django 5.2.16 on 2026-09-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0029_company_recent_order_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyoutreach',
            name='status',
            field=models.CharField(choices=[('pending', 'Σε ουρά'), ('sending', 'Αποστέλλεται'), ('sent', 'Εστάλη'), ('failed', 'Απέτυχε')], default='sent', max_length=10),
        ),
    ]
