# Generated by Django 5.2.16 on 2026-09-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0031_cancel_pending_outreach'),
    ]

    operations = [
        migrations.CreateModel(
            name='GemiSourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('gemi_opendata', 'ΓΕΜΗ Open Data API')], default='gemi_opendata', max_length=32)),
                ('family', models.CharField(choices=[('company_search', 'Company search'), ('company_detail', 'Company detail'), ('reference_data', 'Reference data'), ('document_metadata', 'Document metadata')], max_length=32)),
                ('response_family', models.CharField(max_length=48)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_params', models.JSONField(blank=True, default=dict)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('observation_key', models.CharField(max_length=64, unique=True)),
                ('fetched_at', models.DateTimeField()),
                ('http_status', models.PositiveSmallIntegerField()),
                ('gateway_request_id', models.CharField(blank=True, max_length=80)),
                ('payload_hash', models.CharField(max_length=64)),
                ('result_count', models.PositiveIntegerField(blank=True, null=True)),
                ('response_schema_version', models.PositiveSmallIntegerField()),
                ('normalizer_version', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('record_format_version', models.PositiveSmallIntegerField()),
                ('sanitised_payload', models.JSONField(blank=True, null=True)),
                ('retention_class', models.CharField(choices=[('short', 'Short'), ('standard', 'Standard'), ('audit', 'Audit')], max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'GEMI source record',
                'verbose_name_plural': 'GEMI source records',
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['request_fingerprint', '-fetched_at'], name='gemisrc_request_fetched_idx'), models.Index(fields=['family', '-fetched_at'], name='gemisrc_family_fetched_idx'), models.Index(fields=['expires_at'], name='gemisrc_expires_idx')],
            },
        ),
    ]
