# Generated by Django 5.2.16 on 2026-09-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0033_gemi_reference_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='first_seen_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='gemi_office_source_id',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='incorporation_date_quality',
            field=models.CharField(blank=True, choices=[('valid', 'Valid'), ('missing', 'Missing'), ('invalid', 'Invalid'), ('out_of_range', 'Out of range')], editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_type_source_id',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='municipality_source_id',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='prefecture_source_id',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='status_source_id',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
    ]
