# Generated by Django 5.2.16 on 2026-09-15 07:47

from django.db import migrations, models


def remove_canonical_only_rows(apps, schema_editor):
    """Reverse only. Rows outside the legacy list (legacy_listed=False) exist solely for the canonical A7
    representation -- another KAD version, an earlier period, an activity no longer published. They are
    derived from GEMI records (backfill_gemi_company_activities recreates them), no pre-A7 read ever
    returned them, and they cannot coexist with the pre-A7 unique (company, code, activity_type).
    Every legacy-visible row is kept unchanged."""
    CompanyActivity = apps.get_model("gemiapp", "CompanyActivity")
    CompanyActivity.objects.filter(legacy_listed=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0034_company_gemi_metadata'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='companyactivity',
            name='unique_company_activity',
        ),
        migrations.AddField(
            model_name='companyactivity',
            name='activity_type_normalized',
            field=models.CharField(blank=True, choices=[('primary', 'Κύρια'), ('secondary', 'Δευτερεύουσα'), ('auxiliary', 'Βοηθητική'), ('other', 'Λοιπή'), ('unknown', 'Μη αναγνωρισμένος τύπος')], editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='companyactivity',
            name='current_as_of',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='companyactivity',
            name='date_from',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='companyactivity',
            name='date_from_quality',
            field=models.CharField(blank=True, choices=[('valid', 'Valid'), ('missing', 'Missing'), ('invalid', 'Invalid'), ('out_of_range', 'Out of range')], editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='companyactivity',
            name='date_to',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='companyactivity',
            name='date_to_quality',
            field=models.CharField(blank=True, choices=[('valid', 'Valid'), ('missing', 'Missing'), ('invalid', 'Invalid'), ('out_of_range', 'Out of range')], editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='companyactivity',
            name='in_latest_source',
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='companyactivity',
            name='is_current',
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='companyactivity',
            name='kad_version',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='companyactivity',
            name='legacy_listed',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='companyactivity',
            name='source_key',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        # Forward: nothing. Reverse: runs after the two partial constraints are dropped and before the A7
        # columns are removed and unique_company_activity is restored, so rollback needs no manual step.
        migrations.RunPython(migrations.RunPython.noop, reverse_code=remove_canonical_only_rows, elidable=False),
        migrations.AddConstraint(
            model_name='companyactivity',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_listed', True)), fields=('company', 'code', 'activity_type'), name='unique_company_activity_listed'),
        ),
        migrations.AddConstraint(
            model_name='companyactivity',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key__isnull', False)), fields=('company', 'source_key'), name='unique_company_activity_source_key'),
        ),
    ]
