# Generated by Django 5.2.16 on 2026-09-15 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0035_companyactivity_canonical_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCodeKadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_basis', models.CharField(choices=[('code', 'Ίδιος κωδικός ΚΑΔ')], max_length=16)),
                ('description_matches', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kad_links', to='gemiapp.activitycode')),
                ('gemi_kad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_code_links', to='gemiapp.gemikad')),
            ],
            options={
                'verbose_name': 'ActivityCode ↔ GEMI KAD link',
                'verbose_name_plural': 'ActivityCode ↔ GEMI KAD links',
                'ordering': ['activity_code_id', 'gemi_kad_id'],
                'constraints': [models.UniqueConstraint(fields=('activity_code', 'gemi_kad'), name='unique_activity_code_kad_link')],
            },
        ),
    ]
