# Generated by Django 5.2.16 on 2026-09-15 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0036_activitycode_kad_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('active', 'Active'), ('decaying', 'Decaying'), ('inactive', 'Inactive')], max_length=16)),
                ('priority', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], max_length=16, null=True)),
                ('primary_reason', models.CharField(blank=True, choices=[('new_company', 'New company'), ('active_radar_match', 'Active Radar match'), ('active_opportunity', 'Active opportunity'), ('recent_signal', 'Recent signal'), ('manual', 'Manual')], max_length=32, null=True)),
                ('policy_version', models.PositiveSmallIntegerField()),
                ('monitored_since', models.DateTimeField()),
                ('decay_started_at', models.DateTimeField(blank=True, null=True)),
                ('inactive_since', models.DateTimeField(blank=True, null=True)),
                ('next_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring', to='gemiapp.company')),
            ],
            options={
                'verbose_name': 'Company monitoring',
                'verbose_name_plural': 'Company monitoring',
                'ordering': ['company_id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMonitoringReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('new_company', 'New company'), ('active_radar_match', 'Active Radar match'), ('active_opportunity', 'Active opportunity'), ('recent_signal', 'Recent signal'), ('manual', 'Manual')], max_length=32)),
                ('active', models.BooleanField()),
                ('first_active_at', models.DateTimeField()),
                ('activated_at', models.DateTimeField()),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('activation_count', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('source_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='gemiapp.companymonitoring')),
            ],
            options={
                'ordering': ['monitoring_id', 'reason'],
            },
        ),
        migrations.AddIndex(
            model_name='companymonitoring',
            index=models.Index(fields=['state', 'next_check_at'], name='monitoring_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='companymonitoring',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('next_check_at__isnull', True), ('priority__isnull', True), ('state', 'inactive')), models.Q(('next_check_at__isnull', False), ('priority__isnull', False), ('state__in', ['active', 'decaying'])), _connector='OR'), name='monitoring_state_consistent'),
        ),
        migrations.AddIndex(
            model_name='companymonitoringreason',
            index=models.Index(fields=['reason', 'active'], name='monitoring_reason_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='companymonitoringreason',
            constraint=models.UniqueConstraint(fields=('monitoring', 'reason'), name='unique_monitoring_reason'),
        ),
        migrations.AddConstraint(
            model_name='companymonitoringreason',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('deactivated_at__isnull', True)), models.Q(('active', False), ('deactivated_at__isnull', False)), _connector='OR'), name='monitoring_reason_active_consistent'),
        ),
    ]
