# Generated by Django 5.2.16 on 2026-09-15 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0037_company_monitoring'),
    ]

    operations = [
        migrations.CreateModel(
            name='GemiDiscoveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(max_length=32)),
                ('mode', models.CharField(choices=[('shadow', 'Shadow'), ('ingest', 'Ingest'), ('bootstrap', 'Bootstrap')], max_length=16)),
                ('status', models.CharField(choices=[('running', 'Σε εξέλιξη'), ('success', 'Επιτυχία'), ('incomplete', 'Ημιτελής'), ('anomaly', 'Ανωμαλία'), ('failed', 'Αποτυχία')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('pages_fetched', models.PositiveIntegerField(default=0)),
                ('records_examined', models.PositiveIntegerField(default=0)),
                ('known_records', models.PositiveIntegerField(default=0)),
                ('new_records', models.PositiveIntegerField(default=0)),
                ('late_publication_records', models.PositiveIntegerField(default=0)),
                ('invalid_date_records', models.PositiveIntegerField(default=0)),
                ('duplicate_records', models.PositiveIntegerField(default=0)),
                ('invalid_identifier_records', models.PositiveIntegerField(default=0)),
                ('ingested_records', models.PositiveIntegerField(default=0)),
                ('highest_gemi_number', models.CharField(blank=True, max_length=24)),
                ('previous_high_water_mark', models.CharField(blank=True, max_length=24)),
                ('resulting_high_water_mark', models.CharField(blank=True, max_length=24)),
                ('cursor_advanced', models.BooleanField(default=False)),
                ('overlap_known_records', models.PositiveIntegerField(default=0)),
                ('stop_reason', models.CharField(blank=True, max_length=32)),
                ('anomalies', models.JSONField(blank=True, default=list)),
                ('policy', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'GEMI discovery run',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['stream', '-started_at'], name='discovery_run_stream_idx')],
            },
        ),
        migrations.CreateModel(
            name='GemiDiscoveryCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('uninitialised', 'Χωρίς αρχικοποίηση'), ('ready', 'Έτοιμο'), ('anomaly', 'Ανωμαλία')], default='uninitialised', max_length=16)),
                ('high_water_mark', models.CharField(blank=True, max_length=24)),
                ('high_water_mark_value', models.BigIntegerField(blank=True, null=True)),
                ('bootstrap_method', models.CharField(blank=True, max_length=32)),
                ('bootstrapped_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('anomaly_reason', models.CharField(blank=True, max_length=64)),
                ('anomaly_detected_at', models.DateTimeField(blank=True, null=True)),
                ('last_statistics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gemiapp.gemidiscoveryrun')),
            ],
            options={
                'verbose_name': 'GEMI discovery cursor',
            },
        ),
        migrations.CreateModel(
            name='GemiDiscoveryObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemi_number', models.CharField(db_index=True, max_length=24)),
                ('classification', models.CharField(choices=[('new_incorporation', 'Νέα σύσταση'), ('late_publication', 'Καθυστερημένη δημοσίευση'), ('invalid_date', 'Μη έγκυρη ημερομηνία'), ('known', 'Ήδη γνωστή')], max_length=24)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('incorporation_date_quality', models.CharField(choices=[('valid', 'Valid'), ('missing', 'Missing'), ('invalid', 'Invalid'), ('out_of_range', 'Out of range')], max_length=16)),
                ('company_existed', models.BooleanField()),
                ('page_index', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='gemiapp.gemidiscoveryrun')),
            ],
            options={
                'ordering': ['run_id', 'id'],
                'indexes': [models.Index(fields=['classification'], name='discovery_classification_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'gemi_number'), name='unique_discovery_observation')],
            },
        ),
    ]
