# Generated by Django 5.2.16 on 2026-09-15 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0038_gemi_discovery'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('new_company', 'Νέα επιχείρηση'), ('status_changed', 'Αλλαγή κατάστασης'), ('kad_added', 'Προσθήκη ΚΑΔ'), ('kad_removed', 'Αφαίρεση ΚΑΔ'), ('legal_form_changed', 'Αλλαγή νομικής μορφής'), ('location_changed', 'Αλλαγή έδρας'), ('capital_increase', 'Αύξηση κεφαλαίου'), ('capital_decrease', 'Μείωση κεφαλαίου'), ('new_branch', 'Νέο υποκατάστημα'), ('branch_closed', 'Κλείσιμο υποκαταστήματος'), ('management_change', 'Αλλαγή διοίκησης'), ('merger', 'Συγχώνευση'), ('dissolution', 'Λύση'), ('company_transformation', 'Μετατροπή'), ('other_corporate_event', 'Άλλο εταιρικό γεγονός')], max_length=32)),
                ('source_type', models.CharField(choices=[('discovery', 'Discovery'), ('snapshot_diff', 'Snapshot diff'), ('document_metadata', 'Document metadata'), ('document_analysis', 'Document analysis')], max_length=24)),
                ('rule_version', models.CharField(max_length=64)),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('mode', models.CharField(choices=[('shadow', 'Shadow'), ('live', 'Live')], max_length=8)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('effective_precision', models.CharField(choices=[('none', 'Χωρίς χρόνο πηγής'), ('date', 'Ημερομηνία'), ('datetime', 'Χρονοσήμανση')], max_length=8)),
                ('detected_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signals', to='gemiapp.company')),
            ],
            options={
                'verbose_name': 'Company signal',
                'ordering': ['-detected_at', '-id'],
                'indexes': [models.Index(fields=['company', '-detected_at'], name='signal_company_detected_idx'), models.Index(fields=['signal_type', '-detected_at'], name='signal_type_detected_idx'), models.Index(fields=['mode', '-detected_at'], name='signal_mode_detected_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='company_signal_confidence_range'), models.CheckConstraint(condition=models.Q(models.Q(('effective_at__isnull', True), ('effective_date__isnull', True), ('effective_precision', 'none')), models.Q(('effective_at__isnull', True), ('effective_date__isnull', False), ('effective_precision', 'date')), models.Q(('effective_at__isnull', False), ('effective_date__isnull', True), ('effective_precision', 'datetime')), _connector='OR'), name='company_signal_effective_precision_consistent')],
            },
        ),
    ]
