# Generated by Django 5.2.16 on 2026-09-16 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0039_company_signal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySignalDiscoveryEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discovery_observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produced_signals', to='gemiapp.gemidiscoveryobservation')),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_evidence', to='gemiapp.companysignal')),
            ],
            options={
                'verbose_name': 'Company signal discovery evidence',
                'verbose_name_plural': 'Company signal discovery evidence',
            },
        ),
    ]
