# Generated by Django 5.2.16 on 2026-09-16 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0040_company_signal_discovery_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.PositiveSmallIntegerField()),
                ('normalizer_version', models.PositiveSmallIntegerField()),
                ('state_hash', models.CharField(max_length=64)),
                ('observed_at', models.DateTimeField()),
                ('last_observed_at', models.DateTimeField()),
                ('is_baseline', models.BooleanField()),
                ('status_source_id', models.CharField(blank=True, max_length=32, null=True)),
                ('last_status_change', models.DateField(blank=True, null=True)),
                ('last_status_change_quality', models.CharField(choices=[('valid', 'Valid'), ('missing', 'Missing'), ('invalid', 'Invalid'), ('out_of_range', 'Out of range')], max_length=16)),
                ('legal_type_source_id', models.CharField(blank=True, max_length=32, null=True)),
                ('gemi_office_source_id', models.CharField(blank=True, max_length=32, null=True)),
                ('prefecture_source_id', models.CharField(blank=True, max_length=32, null=True)),
                ('municipality_source_id', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=160, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=16, null=True)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('incorporation_date_quality', models.CharField(choices=[('valid', 'Valid'), ('missing', 'Missing'), ('invalid', 'Invalid'), ('out_of_range', 'Out of range')], max_length=16)),
                ('activities_state', models.JSONField(blank=True, default=list)),
                ('unknown_current_activity_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='gemiapp.company')),
                ('source_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_snapshots', to='gemiapp.gemisourcerecord')),
            ],
            options={
                'verbose_name': 'Company snapshot',
                'ordering': ['-observed_at', '-id'],
                'indexes': [models.Index(fields=['company', '-observed_at'], name='snapshot_company_observed_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('last_observed_at__gte', models.F('observed_at'))), name='snapshot_observation_span_ordered')],
            },
        ),
    ]
