# Generated by Django 5.2.16 on 2026-09-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0041_company_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='GemiRefreshRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Σε εξέλιξη'), ('success', 'Επιτυχία'), ('partial', 'Μερική'), ('failed', 'Αποτυχία')], default='running', max_length=16)),
                ('run_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('due_companies', models.PositiveIntegerField(default=0)),
                ('planned_companies', models.PositiveIntegerField(default=0)),
                ('search_groups', models.PositiveIntegerField(default=0)),
                ('deferred_no_strategy', models.PositiveIntegerField(default=0)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('search_requests', models.PositiveIntegerField(default=0)),
                ('detail_requests', models.PositiveIntegerField(default=0)),
                ('records_examined', models.PositiveIntegerField(default=0)),
                ('target_records_observed', models.PositiveIntegerField(default=0)),
                ('baselines_created', models.PositiveIntegerField(default=0)),
                ('changed_snapshots_created', models.PositiveIntegerField(default=0)),
                ('unchanged_snapshots', models.PositiveIntegerField(default=0)),
                ('search_misses', models.PositiveIntegerField(default=0)),
                ('duplicate_observations_avoided', models.PositiveIntegerField(default=0)),
                ('company_failures', models.PositiveIntegerField(default=0)),
                ('incomplete_groups', models.PositiveIntegerField(default=0)),
                ('group_stats', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'GEMI refresh run',
                'verbose_name_plural': 'GEMI refresh runs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', '-started_at'], name='refresh_run_status_idx')],
            },
        ),
    ]
