# Generated by Django 5.2.16 on 2026-09-16 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0042_gemi_refresh_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySignalSnapshotEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_kind', models.CharField(choices=[('status', 'Status'), ('kad', 'KAD'), ('legal_form', 'Legal form'), ('municipality', 'Municipality')], max_length=16)),
                ('before_source_id', models.CharField(blank=True, max_length=32, null=True)),
                ('after_source_id', models.CharField(blank=True, max_length=32, null=True)),
                ('activity_code', models.CharField(blank=True, max_length=32, null=True)),
                ('kad_version', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signal_evidence_as_current', to='gemiapp.companysnapshot')),
                ('previous_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signal_evidence_as_previous', to='gemiapp.companysnapshot')),
                ('signal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_evidence', to='gemiapp.companysignal')),
            ],
            options={
                'verbose_name': 'Company signal snapshot evidence',
                'verbose_name_plural': 'Company signal snapshot evidence',
                'indexes': [models.Index(fields=['subject_kind'], name='signal_snapshot_subject_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('activity_code__isnull', False), ('after_source_id__isnull', True), ('before_source_id__isnull', True), ('subject_kind', 'kad')), models.Q(('activity_code__isnull', True), ('after_source_id__isnull', False), ('before_source_id__isnull', False), ('kad_version__isnull', True), ('subject_kind__in', ['status', 'legal_form', 'municipality'])), _connector='OR'), name='signal_snapshot_subject_consistent'), models.CheckConstraint(condition=models.Q(('previous_snapshot', models.F('current_snapshot')), _negated=True), name='signal_snapshot_pair_distinct')],
            },
        ),
    ]
