# Generated by Django 5.2.16 on 2026-09-16 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0043_company_signal_snapshot_evidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='organization_name_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(blank=True, max_length=200)),
                ('products', models.CharField(blank=True, max_length=1000)),
                ('target_customers', models.CharField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='gemiapp.organization')),
            ],
            options={
                'verbose_name': 'Organization profile',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('sales_manager', 'Sales manager'), ('sales_user', 'Sales user'), ('viewer', 'Viewer')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='gemiapp.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organization_id', 'id'],
                'indexes': [models.Index(fields=['user', 'organization'], name='org_member_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='unique_organization_member'), models.CheckConstraint(condition=models.Q(('role__in', ['owner', 'admin', 'sales_manager', 'sales_user', 'viewer'])), name='organization_member_role_valid')],
            },
        ),
    ]
