# Generated by Django 5.2.16 on 2026-09-16 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0044_organization_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationICP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_age_months', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_age_months', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='icp', to='gemiapp.organization')),
            ],
            options={
                'verbose_name': 'Organization ICP',
                'verbose_name_plural': 'Organization ICPs',
            },
        ),
        migrations.CreateModel(
            name='OrganizationICPKad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polarity', models.CharField(choices=[('include', 'Include'), ('exclude', 'Exclude')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('icp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kads', to='gemiapp.organizationicp')),
                ('kad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gemiapp.gemikad')),
            ],
            options={
                'verbose_name': 'Organization ICP KAD',
            },
        ),
        migrations.CreateModel(
            name='OrganizationICPLegalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polarity', models.CharField(choices=[('include', 'Include'), ('exclude', 'Exclude')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('icp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_forms', to='gemiapp.organizationicp')),
                ('legal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gemiapp.gemilegaltype')),
            ],
            options={
                'verbose_name': 'Organization ICP legal form',
            },
        ),
        migrations.CreateModel(
            name='OrganizationICPRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('prefecture', 'Prefecture'), ('municipality', 'Municipality')], max_length=16)),
                ('polarity', models.CharField(choices=[('include', 'Include'), ('exclude', 'Exclude')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('icp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='gemiapp.organizationicp')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gemiapp.gemimunicipality')),
                ('prefecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gemiapp.gemiprefecture')),
            ],
            options={
                'verbose_name': 'Organization ICP region',
            },
        ),
        migrations.CreateModel(
            name='OrganizationICPSignalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('new_company', 'Νέα επιχείρηση'), ('status_changed', 'Αλλαγή κατάστασης'), ('kad_added', 'Προσθήκη ΚΑΔ'), ('kad_removed', 'Αφαίρεση ΚΑΔ'), ('legal_form_changed', 'Αλλαγή νομικής μορφής'), ('location_changed', 'Αλλαγή έδρας'), ('capital_increase', 'Αύξηση κεφαλαίου'), ('capital_decrease', 'Μείωση κεφαλαίου'), ('new_branch', 'Νέο υποκατάστημα'), ('branch_closed', 'Κλείσιμο υποκαταστήματος'), ('management_change', 'Αλλαγή διοίκησης'), ('merger', 'Συγχώνευση'), ('dissolution', 'Λύση'), ('company_transformation', 'Μετατροπή'), ('other_corporate_event', 'Άλλο εταιρικό γεγονός')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('icp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_types', to='gemiapp.organizationicp')),
            ],
            options={
                'verbose_name': 'Organization ICP signal type',
            },
        ),
        migrations.CreateModel(
            name='OrganizationICPStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polarity', models.CharField(choices=[('include', 'Include'), ('exclude', 'Exclude')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('icp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='gemiapp.organizationicp')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gemiapp.gemicompanystatus')),
            ],
            options={
                'verbose_name': 'Organization ICP status',
                'verbose_name_plural': 'Organization ICP statuses',
            },
        ),
        migrations.AddConstraint(
            model_name='organizationicp',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_age_months__isnull', True), ('maximum_age_months__isnull', True), ('minimum_age_months__lte', models.F('maximum_age_months')), _connector='OR'), name='icp_age_range_ordered'),
        ),
        migrations.AddConstraint(
            model_name='organizationicp',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('minimum_age_months__isnull', True), ('minimum_age_months__gte', 0), _connector='OR'), models.Q(('maximum_age_months__isnull', True), ('maximum_age_months__gte', 0), _connector='OR')), name='icp_age_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='organizationicpkad',
            constraint=models.UniqueConstraint(fields=('icp', 'kad'), name='unique_icp_kad'),
        ),
        migrations.AddConstraint(
            model_name='organizationicpkad',
            constraint=models.CheckConstraint(condition=models.Q(('polarity__in', ['include', 'exclude'])), name='icp_kad_polarity_valid'),
        ),
        migrations.AddConstraint(
            model_name='organizationicplegalform',
            constraint=models.UniqueConstraint(fields=('icp', 'legal_type'), name='unique_icp_legal_form'),
        ),
        migrations.AddConstraint(
            model_name='organizationicplegalform',
            constraint=models.CheckConstraint(condition=models.Q(('polarity__in', ['include', 'exclude'])), name='icp_legal_form_polarity_valid'),
        ),
        migrations.AddConstraint(
            model_name='organizationicpregion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('level', 'prefecture'), ('municipality__isnull', True), ('prefecture__isnull', False)), models.Q(('level', 'municipality'), ('municipality__isnull', False), ('prefecture__isnull', True)), _connector='OR'), name='icp_region_level_consistent'),
        ),
        migrations.AddConstraint(
            model_name='organizationicpregion',
            constraint=models.UniqueConstraint(condition=models.Q(('prefecture__isnull', False)), fields=('icp', 'prefecture'), name='unique_icp_prefecture'),
        ),
        migrations.AddConstraint(
            model_name='organizationicpregion',
            constraint=models.UniqueConstraint(condition=models.Q(('municipality__isnull', False)), fields=('icp', 'municipality'), name='unique_icp_municipality'),
        ),
        migrations.AddConstraint(
            model_name='organizationicpregion',
            constraint=models.CheckConstraint(condition=models.Q(('polarity__in', ['include', 'exclude'])), name='icp_region_polarity_valid'),
        ),
        migrations.AddConstraint(
            model_name='organizationicpsignaltype',
            constraint=models.UniqueConstraint(fields=('icp', 'signal_type'), name='unique_icp_signal_type'),
        ),
        migrations.AddConstraint(
            model_name='organizationicpsignaltype',
            constraint=models.CheckConstraint(condition=models.Q(('signal_type__in', ['new_company', 'status_changed', 'kad_added', 'kad_removed', 'legal_form_changed', 'location_changed', 'capital_increase', 'capital_decrease', 'new_branch', 'branch_closed', 'management_change', 'merger', 'dissolution', 'company_transformation', 'other_corporate_event'])), name='icp_signal_type_known'),
        ),
        migrations.AddConstraint(
            model_name='organizationicpstatus',
            constraint=models.UniqueConstraint(fields=('icp', 'status'), name='unique_icp_status'),
        ),
        migrations.AddConstraint(
            model_name='organizationicpstatus',
            constraint=models.CheckConstraint(condition=models.Q(('polarity__in', ['include', 'exclude'])), name='icp_status_polarity_valid'),
        ),
    ]
