# Generated by Django 5.2.16 on 2026-09-16 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0045_organization_icp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRadar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=False)),
                ('score_threshold', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radars', to='gemiapp.organization')),
            ],
            options={
                'verbose_name': 'Organization radar',
                'ordering': ['organization_id', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationRadarExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('kad', 'KAD'), ('prefecture', 'Prefecture'), ('municipality', 'Municipality'), ('legal_form', 'Legal form')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gemiapp.gemikad')),
                ('legal_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gemiapp.gemilegaltype')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gemiapp.gemimunicipality')),
                ('prefecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gemiapp.gemiprefecture')),
                ('radar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='gemiapp.organizationradar')),
            ],
            options={
                'verbose_name': 'Organization radar exclusion',
            },
        ),
        migrations.CreateModel(
            name='OrganizationRadarKad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gemiapp.gemikad')),
                ('radar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kads', to='gemiapp.organizationradar')),
            ],
            options={
                'verbose_name': 'Organization radar KAD',
            },
        ),
        migrations.CreateModel(
            name='OrganizationRadarLegalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gemiapp.gemilegaltype')),
                ('radar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_forms', to='gemiapp.organizationradar')),
            ],
            options={
                'verbose_name': 'Organization radar legal form',
            },
        ),
        migrations.CreateModel(
            name='OrganizationRadarRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('prefecture', 'Prefecture'), ('municipality', 'Municipality')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gemiapp.gemimunicipality')),
                ('prefecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gemiapp.gemiprefecture')),
                ('radar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='gemiapp.organizationradar')),
            ],
            options={
                'verbose_name': 'Organization radar region',
            },
        ),
        migrations.CreateModel(
            name='OrganizationRadarSignalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('new_company', 'Νέα επιχείρηση'), ('status_changed', 'Αλλαγή κατάστασης'), ('kad_added', 'Προσθήκη ΚΑΔ'), ('kad_removed', 'Αφαίρεση ΚΑΔ'), ('legal_form_changed', 'Αλλαγή νομικής μορφής'), ('location_changed', 'Αλλαγή έδρας'), ('capital_increase', 'Αύξηση κεφαλαίου'), ('capital_decrease', 'Μείωση κεφαλαίου'), ('new_branch', 'Νέο υποκατάστημα'), ('branch_closed', 'Κλείσιμο υποκαταστήματος'), ('management_change', 'Αλλαγή διοίκησης'), ('merger', 'Συγχώνευση'), ('dissolution', 'Λύση'), ('company_transformation', 'Μετατροπή'), ('other_corporate_event', 'Άλλο εταιρικό γεγονός')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('radar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_types', to='gemiapp.organizationradar')),
            ],
            options={
                'verbose_name': 'Organization radar signal type',
            },
        ),
        migrations.AddIndex(
            model_name='organizationradar',
            index=models.Index(fields=['organization', 'active'], name='org_radar_org_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationradar',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='org_radar_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='organizationradar',
            constraint=models.CheckConstraint(condition=models.Q(('score_threshold__isnull', True), models.Q(('score_threshold__gte', 0), ('score_threshold__lte', 100)), _connector='OR'), name='org_radar_score_threshold_range'),
        ),
        migrations.AddConstraint(
            model_name='organizationradarexclusion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kad__isnull', False), ('legal_type__isnull', True), ('municipality__isnull', True), ('prefecture__isnull', True), ('subject', 'kad')), models.Q(('kad__isnull', True), ('legal_type__isnull', True), ('municipality__isnull', True), ('prefecture__isnull', False), ('subject', 'prefecture')), models.Q(('kad__isnull', True), ('legal_type__isnull', True), ('municipality__isnull', False), ('prefecture__isnull', True), ('subject', 'municipality')), models.Q(('kad__isnull', True), ('legal_type__isnull', False), ('municipality__isnull', True), ('prefecture__isnull', True), ('subject', 'legal_form')), _connector='OR'), name='org_radar_exclusion_subject_consistent'),
        ),
        migrations.AddConstraint(
            model_name='organizationradarexclusion',
            constraint=models.UniqueConstraint(condition=models.Q(('kad__isnull', False)), fields=('radar', 'kad'), name='unique_org_radar_excluded_kad'),
        ),
        migrations.AddConstraint(
            model_name='organizationradarexclusion',
            constraint=models.UniqueConstraint(condition=models.Q(('prefecture__isnull', False)), fields=('radar', 'prefecture'), name='unique_org_radar_excluded_prefecture'),
        ),
        migrations.AddConstraint(
            model_name='organizationradarexclusion',
            constraint=models.UniqueConstraint(condition=models.Q(('municipality__isnull', False)), fields=('radar', 'municipality'), name='unique_org_radar_excluded_municipality'),
        ),
        migrations.AddConstraint(
            model_name='organizationradarexclusion',
            constraint=models.UniqueConstraint(condition=models.Q(('legal_type__isnull', False)), fields=('radar', 'legal_type'), name='unique_org_radar_excluded_legal_form'),
        ),
        migrations.AddConstraint(
            model_name='organizationradarkad',
            constraint=models.UniqueConstraint(fields=('radar', 'kad'), name='unique_org_radar_kad'),
        ),
        migrations.AddConstraint(
            model_name='organizationradarlegalform',
            constraint=models.UniqueConstraint(fields=('radar', 'legal_type'), name='unique_org_radar_legal_form'),
        ),
        migrations.AddConstraint(
            model_name='organizationradarregion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('level', 'prefecture'), ('municipality__isnull', True), ('prefecture__isnull', False)), models.Q(('level', 'municipality'), ('municipality__isnull', False), ('prefecture__isnull', True)), _connector='OR'), name='org_radar_region_level_consistent'),
        ),
        migrations.AddConstraint(
            model_name='organizationradarregion',
            constraint=models.UniqueConstraint(condition=models.Q(('prefecture__isnull', False)), fields=('radar', 'prefecture'), name='unique_org_radar_prefecture'),
        ),
        migrations.AddConstraint(
            model_name='organizationradarregion',
            constraint=models.UniqueConstraint(condition=models.Q(('municipality__isnull', False)), fields=('radar', 'municipality'), name='unique_org_radar_municipality'),
        ),
        migrations.AddConstraint(
            model_name='organizationradarsignaltype',
            constraint=models.UniqueConstraint(fields=('radar', 'signal_type'), name='unique_org_radar_signal_type'),
        ),
        migrations.AddConstraint(
            model_name='organizationradarsignaltype',
            constraint=models.CheckConstraint(condition=models.Q(('signal_type__in', ['new_company', 'status_changed', 'kad_added', 'kad_removed', 'legal_form_changed', 'location_changed', 'capital_increase', 'capital_decrease', 'new_branch', 'branch_closed', 'management_change', 'merger', 'dissolution', 'company_transformation', 'other_corporate_event'])), name='org_radar_signal_type_known'),
        ),
    ]
