# Generated by Django 5.2.16 on 2026-09-16 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0046_organization_radar'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Industry template',
                'ordering': ['slug'],
                'constraints': [models.CheckConstraint(condition=models.Q(('slug', ''), _negated=True), name='industry_template_slug_not_blank'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='industry_template_name_not_blank')],
            },
        ),
        migrations.CreateModel(
            name='IndustryTemplateKad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='gemiapp.gemikad')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kads', to='gemiapp.industrytemplate')),
            ],
            options={
                'verbose_name': 'Industry template KAD',
                'constraints': [models.UniqueConstraint(fields=('template', 'kad'), name='unique_industry_template_kad')],
            },
        ),
    ]
