# Generated by Django 5.2.16 on 2026-09-18 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0047_industry_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('score_class', models.CharField(choices=[('priority', 'Priority'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=16)),
                ('score_rule_version', models.CharField(max_length=64)),
                ('match_rule_version', models.CharField(max_length=64)),
                ('scored_as_of', models.DateTimeField()),
                ('primary_reason_code', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('new', 'New'), ('viewed', 'Viewed'), ('saved', 'Saved'), ('assigned', 'Assigned'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('follow_up', 'Follow up'), ('won', 'Won'), ('lost', 'Lost'), ('not_relevant', 'Not relevant'), ('do_not_contact', 'Do not contact')], default='new', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='gemiapp.company')),
                ('first_signal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_opportunities', to='gemiapp.companysignal')),
                ('latest_signal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='latest_opportunities', to='gemiapp.companysignal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='gemiapp.organization')),
                ('radar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='gemiapp.organizationradar')),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-score', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityScoreComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('awarded_points', models.PositiveSmallIntegerField()),
                ('max_points', models.PositiveSmallIntegerField()),
                ('reason_code', models.CharField(max_length=40)),
                ('position', models.PositiveSmallIntegerField()),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_components', to='gemiapp.opportunity')),
            ],
            options={
                'verbose_name': 'Opportunity score component',
                'ordering': ['opportunity_id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityScoreEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('kad', 'KAD'), ('signal_type', 'Signal type'), ('region', 'Region'), ('legal_form', 'Legal form'), ('freshness', 'Freshness')], max_length=16)),
                ('position', models.PositiveSmallIntegerField()),
                ('kad_code', models.CharField(blank=True, max_length=32, null=True)),
                ('kad_version', models.CharField(blank=True, max_length=16, null=True)),
                ('signal_type', models.CharField(blank=True, max_length=32, null=True)),
                ('region_level', models.CharField(blank=True, choices=[('prefecture', 'Prefecture'), ('municipality', 'Municipality')], max_length=16, null=True)),
                ('region_source_id', models.CharField(blank=True, max_length=32, null=True)),
                ('legal_type_source_id', models.CharField(blank=True, max_length=32, null=True)),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
                ('scored_as_of', models.DateTimeField(blank=True, null=True)),
                ('age_seconds', models.BigIntegerField(blank=True, null=True)),
                ('band_points', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='gemiapp.opportunityscorecomponent')),
            ],
            options={
                'verbose_name': 'Opportunity score evidence',
                'verbose_name_plural': 'Opportunity score evidence',
                'ordering': ['component_id', 'position'],
            },
        ),
        migrations.CreateModel(
            name='OpportunitySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('scored_as_of', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='gemiapp.opportunity')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_links', to='gemiapp.companysignal')),
            ],
            options={
                'verbose_name': 'Opportunity signal',
                'ordering': ['opportunity_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['organization', '-score'], name='opportunity_org_score_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['organization', 'status'], name='opportunity_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['company'], name='opportunity_company_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.UniqueConstraint(fields=('organization', 'radar', 'company'), name='unique_opportunity_identity'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='opportunity_score_range'),
        ),
        migrations.AddConstraint(
            model_name='opportunityscorecomponent',
            constraint=models.UniqueConstraint(fields=('opportunity', 'code'), name='unique_opportunity_score_component'),
        ),
        migrations.AddConstraint(
            model_name='opportunityscorecomponent',
            constraint=models.CheckConstraint(condition=models.Q(('awarded_points__lte', models.F('max_points'))), name='opportunity_component_points_within_max'),
        ),
        migrations.AddConstraint(
            model_name='opportunityscoreevidence',
            constraint=models.UniqueConstraint(fields=('component', 'position'), name='unique_opportunity_evidence_position'),
        ),
        migrations.AddConstraint(
            model_name='opportunityscoreevidence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('detected_at__isnull', True), ('kad_code__isnull', False), ('kind', 'kad'), ('legal_type_source_id__isnull', True), ('region_level__isnull', True), ('signal_type__isnull', True)), models.Q(('detected_at__isnull', True), ('kad_code__isnull', True), ('kind', 'signal_type'), ('legal_type_source_id__isnull', True), ('region_level__isnull', True), ('signal_type__isnull', False)), models.Q(('detected_at__isnull', True), ('kad_code__isnull', True), ('kind', 'region'), ('legal_type_source_id__isnull', True), ('region_level__isnull', False), ('region_source_id__isnull', False), ('signal_type__isnull', True)), models.Q(('detected_at__isnull', True), ('kad_code__isnull', True), ('kind', 'legal_form'), ('legal_type_source_id__isnull', False), ('region_level__isnull', True), ('signal_type__isnull', True)), models.Q(('age_seconds__isnull', False), ('band_points__isnull', False), ('detected_at__isnull', False), ('kad_code__isnull', True), ('kind', 'freshness'), ('legal_type_source_id__isnull', True), ('region_level__isnull', True), ('scored_as_of__isnull', False), ('signal_type__isnull', True)), _connector='OR'), name='opportunity_evidence_kind_consistent'),
        ),
        migrations.AddConstraint(
            model_name='opportunitysignal',
            constraint=models.UniqueConstraint(fields=('opportunity', 'signal'), name='unique_opportunity_signal'),
        ),
        migrations.AddConstraint(
            model_name='opportunitysignal',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='opportunity_signal_score_range'),
        ),
    ]
