# Generated by Django 5.2.16 on 2026-09-18 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0048_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_opportunities', to='gemiapp.organizationmember'),
        ),
    ]
