# Generated by Django 5.2.16 on 2026-09-18 23:24

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0049_opportunity_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity_notes', to='gemiapp.organizationmember')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='gemiapp.opportunity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_notes', to='gemiapp.organization')),
            ],
            options={
                'verbose_name': 'Opportunity note',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'opportunity', '-created_at'], name='opportunity_note_read_idx')],
                'constraints': [models.CheckConstraint(condition=django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length('body'), 0), name='opportunity_note_body_not_empty'), models.CheckConstraint(condition=django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('body'), 4000), name='opportunity_note_body_max_length')],
            },
        ),
    ]
