# Generated by Django 5.2.16 on 2026-09-19 01:49

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0050_opportunity_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_on', models.DateField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_opportunity_tasks', to='gemiapp.organizationmember')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_opportunity_tasks', to='gemiapp.organizationmember')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunity_tasks', to='gemiapp.organizationmember')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='gemiapp.opportunity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_tasks', to='gemiapp.organization')),
            ],
            options={
                'verbose_name': 'Opportunity task',
                'ordering': ['due_on', 'created_at', 'id'],
                'indexes': [models.Index(fields=['organization', 'opportunity', 'due_on'], name='opportunity_task_read_idx')],
                'constraints': [models.CheckConstraint(condition=django.db.models.lookups.GreaterThan(django.db.models.functions.text.Length('title'), 0), name='opportunity_task_title_not_empty'), models.CheckConstraint(condition=django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('title'), 200), name='opportunity_task_title_max_length'), models.CheckConstraint(condition=models.Q(('completed_by__isnull', True), ('completed_at__isnull', False), _connector='OR'), name='opportunity_task_completer_needs_completion')],
            },
        ),
    ]
