# Generated by Django 5.2.16 on 2026-09-19 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0051_opportunity_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationContactSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('company', 'Company')], max_length=16)),
                ('contact_value', models.CharField(max_length=64)),
                ('reason', models.CharField(choices=[('explicit_objection', 'Explicit objection'), ('email_unsubscribe', 'Email unsubscribe'), ('call_objection', 'Call objection'), ('compliance_registry', 'Compliance registry'), ('manual', 'Manual')], max_length=32)),
                ('source', models.CharField(choices=[('manual', 'Manual')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contact_suppressions', to='gemiapp.organizationmember')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_suppressions', to='gemiapp.organization')),
            ],
            options={
                'verbose_name': 'Organization contact suppression',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'contact_type', 'contact_value'), name='unique_organization_contact_suppression'), models.CheckConstraint(condition=models.Q(('contact_type__in', ['company'])), name='contact_suppression_known_type'), models.CheckConstraint(condition=models.Q(('contact_value', ''), _negated=True), name='contact_suppression_value_not_empty'), models.CheckConstraint(condition=models.Q(('reason__in', ['explicit_objection', 'email_unsubscribe', 'call_objection', 'compliance_registry', 'manual'])), name='contact_suppression_known_reason'), models.CheckConstraint(condition=models.Q(('contact_type', 'company'), ('reason', 'email_unsubscribe'), _negated=True), name='contact_suppression_company_reason'), models.CheckConstraint(condition=models.Q(('source__in', ['manual'])), name='contact_suppression_known_source')],
            },
        ),
    ]
