# Generated by Django 5.2.16 on 2026-09-19 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0052_organization_contact_suppression'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('opportunity_saved', 'Opportunity saved'), ('opportunity_assigned', 'Opportunity assigned'), ('opportunity_reassigned', 'Opportunity reassigned'), ('opportunity_status_changed', 'Opportunity status changed'), ('note_added', 'Note added'), ('task_created', 'Task created'), ('task_completed', 'Task completed'), ('suppression_added', 'Suppression added'), ('suppression_reapplied', 'Suppression reapplied')], max_length=32)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('reason', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='gemiapp.organizationmember')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gemiapp.company')),
                ('new_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gemiapp.organizationmember')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gemiapp.opportunitynote')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='gemiapp.opportunity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='gemiapp.organization')),
                ('previous_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gemiapp.organizationmember')),
                ('suppression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gemiapp.organizationcontactsuppression')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gemiapp.opportunitytask')),
            ],
            options={
                'verbose_name': 'Organization audit event',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'company', '-created_at'], name='org_audit_company_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('action__in', ['opportunity_saved', 'opportunity_assigned', 'opportunity_reassigned', 'opportunity_status_changed', 'note_added', 'task_created', 'task_completed', 'suppression_added', 'suppression_reapplied'])), name='organization_audit_event_known_action')],
            },
        ),
    ]
