# Generated by Django 5.2.16 on 2026-09-19 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0053_organization_audit_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_opportunity', 'New opportunity'), ('priority_signal', 'Priority signal'), ('radar_match', 'Radar match'), ('task_due', 'Task due'), ('assignment', 'Assignment')], max_length=24)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gemiapp.opportunity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='gemiapp.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='gemiapp.organizationmember')),
                ('source_audit_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gemiapp.organizationauditevent')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gemiapp.opportunitytask')),
            ],
            options={
                'verbose_name': 'Organization notification',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'recipient', '-created_at'], name='org_notification_inbox_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('notification_type__in', ['new_opportunity', 'priority_signal', 'radar_match', 'task_due', 'assignment'])), name='organization_notification_known_type'), models.CheckConstraint(condition=models.Q(models.Q(('notification_type', 'task_due'), _negated=True), models.Q(('task__isnull', False), ('due_on__isnull', False), ('opportunity__isnull', False)), _connector='OR'), name='organization_notification_task_due_shape'), models.CheckConstraint(condition=models.Q(models.Q(('notification_type', 'assignment'), _negated=True), ('opportunity__isnull', False), _connector='OR'), name='organization_notification_assignment_shape'), models.UniqueConstraint(condition=models.Q(('notification_type', 'task_due')), fields=('recipient', 'task', 'due_on'), name='unique_task_due_notification'), models.UniqueConstraint(condition=models.Q(('notification_type', 'assignment')), fields=('recipient', 'source_audit_event'), name='unique_assignment_notification')],
            },
        ),
    ]
