# Generated by Django 5.2.16 on 2026-09-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0054_organization_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='GemiRequestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('lane', models.PositiveSmallIntegerField(choices=[(1, 'DISCOVERY'), (2, 'DIGEST_IMPORT'), (3, 'MONITORED_REFRESH'), (4, 'DOCUMENTS')])),
                ('attempt', models.PositiveSmallIntegerField()),
                ('outcome', models.CharField(choices=[('success', '2xx'), ('rate_limited', '429'), ('server_error', '5xx'), ('client_error', '4xx other than 429'), ('transport_error', 'No HTTP response (timeout, DNS, refused)'), ('budget_timeout', 'No slot within max_wait -- nothing was sent'), ('budget_unavailable', 'Shared budget store failed -- nothing was sent')], max_length=24)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('budget_wait_ms', models.PositiveIntegerField(default=0)),
                ('endpoint', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'GEMI request attempt',
                'verbose_name_plural': 'GEMI request attempts',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['occurred_at', 'outcome'], name='gemireq_occurred_outcome_idx')],
            },
        ),
    ]
