# Generated by Django 5.2.16 on 2026-09-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0056_legacy_radar_migration_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDeliverySuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reason', models.CharField(choices=[('hard_bounce', 'Hard bounce'), ('blocked', 'Blocked')], max_length=20)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Μη παραδόσιμο email',
                'verbose_name_plural': 'Μη παραδόσιμα email',
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
