# Generated by Django 5.2.16 on 2026-10-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemiapp', '0057_email_delivery_suppression'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemidiscoveryobservation',
            name='ingest_outcome',
            field=models.CharField(blank=True, choices=[('created', 'Company created from the search payload'), ('already_local', 'Company already stored: never written over'), ('quarantined_date', 'No Company: the incorporation date could not be stored as it is'), ('write_failed', 'No Company: the write failed and was rolled back')], default='', max_length=24),
        ),
    ]
